---
- name: Установка Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Настройка index.html из шаблона
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache  # Это вызовет handler

- name: Запуск и автозагрузка Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Проверка доступности сайта (код 200)
  uri:
    url: "http://{{ ansible_default_ipv4.address }}"
    status_code: 200